In [18]:
import pandas as pd
import numpy as np

In [2]:
sales = pd.read_csv('sales_data_sample.csv', encoding='latin')

In [3]:
sales

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [4]:
sales.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='object')

In [10]:
data = pd.DataFrame(sales.loc[:50,['ORDERNUMBER','CUSTOMERNAME','ADDRESSLINE1','POSTALCODE','STATUS',]])

,ORDERNUMBER,CUSTOMERNAME,ADDRESSLINE1,POSTALCODE,STATUS
0,10107,Land of Toys Inc.,897 Long Airport Avenue,10022,Shipped
1,10121,Reims Collectables,59 rue de l'Abbaye,51100,Shipped
2,10134,Lyon Souveniers,27 rue du Colonel Pierre Avia,75508,Shipped
3,10145,Toys4GrownUps.com,78934 Hillside Dr.,90003,Shipped
4,10159,Corporate Gift Ideas Co.,7734 Strong St.,NaN,Shipped
5,10168,Technics Stores Inc.,9408 Furth Circle,94217,Shipped
6,10180,Daedalus Designs Imports,"184, chausse de Tournai",59000,Shipped
7,10188,Herkku Gifts,"Drammen 121, PR 744 Sentrum",N 5804,Shipped
8,10201,Mini Wheels Co.,5557 North Pendale Street,NaN,Shipped
9,10211,Auto Canal Petit,"25, rue Lauriston",75016,Shipped
10,10223,"Australian Collectors, Co.",636 St Kilda Road,3004,Shipped
11,10237,Vitachrome Inc.,2678 Kingston Rd.,10022,Shipped
12,10251,Tekni Collectables Inc.,7476 Moss Rd.,94019,Shipped
13,10263,Gift Depot Inc.,25593 South Bay Ln.,97562,Shipped
14,10275,La Rochelle Gifts,"67, rue des Cinquante Otages",44000,Shipped
15,10285,Marta's Replicas Co.,39323 Spinnaker Dr.,51247,Shipped
16,10299,"Toys of Finland, Co.",Keskuskatu 45,21240,Shipped
17,10309,Baane Mini Imports,Erling Skakkes gate 78,4110,Shipped
18,10318,Diecast Classics Inc.,7586 Pompton St.,70267,Shipped
19,10329,Land of Toys Inc.,897 Long Airport Avenue,10022,Shipped
20,10341,Salzburg Collectables,Geislweg 14,5020,Shipped
21,10361,Souveniers And Things Co.,"Monitor Money Building, 815 Pacific Hwy",2067,Shipped
22,10375,La Rochelle Gifts,"67, rue des Cinquante Otages",44000,Shipped
23,10388,FunGiftIdeas.com,1785 First Street,50553,Shipped
24,10403,"UK Collectables, Ltd.",Berkeley Gardens 12 Brewery,WX1 6LT,Shipped
25,10417,Euro Shopping Channel,"C/ Moralzarzal, 86",28034,Disputed
26,10103,Baane Mini Imports,Erling Skakkes gate 78,4110,Shipped
27,10112,"Volvo Model Replicas, Co",Berguvsvï¿½gen 8,S-958 22,Shipped
28,10126,"Corrida Auto Replicas, Ltd","C/ Araquil, 67",28023,Shipped
29,10140,Technics Stores Inc.,9408 Furth Circle,94217,Shipped
30,10150,"Dragon Souveniers, Ltd.","Bronz Sok., Bronz Apt. 3/6 Tesvikiye",79903,Shipped
31,10163,Classic Legends Inc.,5905 Pompton St.,10022,Shipped
32,10174,"Australian Gift Network, Co",31 Duncan St. West End,4101,Shipped
33,10183,"Classic Gift Ideas, Inc",782 First Street,71270,Shipped
34,10194,"Saveley & Henriot, Co.","2, rue du Commerce",69004,Shipped
35,10206,Canadian Gift Exchange Network,1900 Oak St.,V3F 2K1,Shipped
36,10215,West Coast Collectables Co.,3675 Furth Circle,94019,Shipped
37,10228,Cambridge Collectables Co.,4658 Baden Av.,51247,Shipped
38,10245,Super Scale Inc.,567 North Pendale Street,97823,Shipped
39,10258,"Tokyo Collectables, Ltd",2-2-8 Roppongi,106-0032,Shipped
40,10270,Souveniers And Things Co.,"Monitor Money Building, 815 Pacific Hwy",2067,Shipped
41,10280,Amica Models & Co.,Via Monte Bianco 34,10100,Shipped
42,10291,Scandinavian Gift Ideas,?kergatan 24,S-844 67,Shipped
43,10304,Auto Assoc. & Cie.,"67, avenue de l'Europe",78000,Shipped
44,10312,Mini Gifts Distributors Ltd.,5677 Strong St.,97562,Shipped
45,10322,Online Diecast Creations Co.,2304 Long Airport Avenue,62005,Shipped
46,10333,Mini Wheels Co.,5557 North Pendale Street,NaN,Shipped
47,10347,"Australian Collectors, Co.",636 St Kilda Road,3004,Shipped
48,10357,Mini Gifts Distributors Ltd.,5677 Strong St.,97562,Shipped
49,10369,Collectables For Less Inc.,7825 Douglas Av.,58339,Shipped
50,10381,Corporate Gift Ideas Co.,7734 Strong St.,NaN,Shipped

In [11]:
data.to_csv('new_sales.csv')

In [17]:
users = pd.read_json('users.json')
users

   id first_name  last_name                   email  gender      ip_address
0   1   Jeanette  Penddreth  jpenddreth0@census.gov  Female     26.58.193.2
1   2    Giavani   Frediani   gfrediani1@senate.gov    Male   229.179.4.212
2   3      Noell        Bea     nbea2@imageshack.us  Female  180.66.162.255
3   4    Willard      Valek          wvalek3@vk.com    Male    67.76.188.26

In [19]:
dfj = pd.DataFrame(np.random.randn(5,2), columns=['record1', 'record2'])
dfj.to_json('new_users.json', orient='columns')

In [20]:
import requests

In [21]:
url = 'http://jsonplaceholder.typicode.com/users'
res = requests.get(url)

In [22]:
all_users = res.json()
all_users[0]

{'id': 1,
 'name': 'Leanne Graham',
 'username': 'Bret',
 'email': 'Sincere@april.biz',
 'address': {'street': 'Kulas Light',
  'suite': 'Apt. 556',
  'city': 'Gwenborough',
  'zipcode': '92998-3874',
  'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
 'phone': '1-770-736-8031 x56442',
 'website': 'hildegard.org',
 'company': {'name': 'Romaguera-Crona',
  'catchPhrase': 'Multi-layered client-server neural-net',
  'bs': 'harness real-time e-markets'}}

In [23]:
users = pd.DataFrame(all_users)
users

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [24]:
users.to_jason('api_response.json',orient='records')

AttributeError: 'DataFrame' object has no attribute 'to_jason'